typography_spectrum: 0.2197869443334639
color:
  brandStrength: 0.7102129175327718
  lightness: 0.05802704021334648
  saturation: 0.18630372756160796
  rhythmicContrast: 0.9068017895333469
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.7812756586354226
name: TechTy
title: SportstechTy
description: Disrupting Sports with Tech
